# Generated by Django 6.0.3 on 2026-03-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=['datetime', 'timezone'], max_length=250),
            preserve_default=False,
        ),
    ]
