# Generated by Django 6.0.1 on 2026-02-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_sociallink_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='paltform',
            new_name='platform',
        ),
    ]
